services:

  # Your data warehouse — where the Netflix data will live
  postgres:
    image: postgres:16
    container_name: netflix_postgres
    environment:
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_DB: netflix_dw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Airflow — runs everything (webserver + scheduler) in one process
  airflow:
    image: apache/airflow:2.9.3
    container_name: netflix_airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _PIP_ADDITIONAL_REQUIREMENTS: 'pandas psycopg2-binary'
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    command: standalone

volumes:
  postgres_data: